### ISSUE TITLE
Rename the output APK

### ISSUE THREAD

**Issue by KerryRitter** [beevelop/apk-signer#14]
Great tool, thank you for releasing it!

Is there a way to rename the APK via the CLI? I.e. from "android-release-unsigned.apk" to "myapp.apk" instead of "android-release.apk"?

**Comment by beevelop** [comment]
The resulting name depends on the input file's name (see https://github.com/beevelop/apk-signer/blob/master/apk-signer#L46). I'm not quite sure where the `-release` gets appended. At least you should be able to get it to `myapp-release.apk` by renaming the input file respectively.

**Comment by beevelop** [comment]
Feel free to reopen, if there are any further questions.

**Comment by tfcardoso** [comment]
@beevelop, @KerryRitter  Wouldn't be good if there was the option:

     -o, --output Define output name for signed apk

**Comment by beevelop** [comment]
@tfcardoso Sounds like a good proposal. I didn't deal with this lib for quite some time. I'd glad to merge respective pull requests 👍

**Comment by tfcardoso** [comment]
@beevelop Please review https://github.com/beevelop/apk-signer/pull/15

Go easy on me, its my first PR on github and JS is not my language :)

**Comment by beevelop** [comment]
@tfcardoso Looks good 👍 Thank you for the contribution. Will do a release containing those changes.
